### ISSUE TITLE
Unity: Failed to import package with error: Couldn't decompress package

### ISSUE THREAD

**Issue by oscarqht** [bengreenier/unity-package-decrypt#2]
# Issue Report

## What happened?

1. I got the encrypted assetstore package file and the decryption key;
2. I use the following nodejs code to decrypt the package;
3. Then I import the decrypted file into Unity;
4. Unity told me he couldn't decompress the package :(

## Where I got the package file and key?

I send request to `https://kharma.unity3d.com/api/en-US/content/download/<ID>.json` to fetch the package file's download URL and decryption key. Here is an example of the response: 

```json
{
    "download": {
        "link": {
            "id": "64131",
            "type": "content"
        },
        "progress": "100",
        "filename_safe_package_name": "VRTK - Virtual Reality Toolkit - VR Toolkit",
        "key": "e81fcf96affbb4925a23ad15ab1c8cce16de0e9c2fb37662c5070cd39b76755902108a0d45313c49bb57f2f694b22746",
        "filename_safe_category_name": "Scripting",
        "url": "http://d2ujflorbtfzji.cloudfront.net/download/be1d7bfb-c6a9-459d-97a7-2beaed508c48",
        "filename_safe_publisher_name": "Sysdia Solutions Ltd",
        "id": "64131"
    }
}
```

## How I decrypt the file?

I basically copy paste the test code from [here](https://github.com/bengreenier/unity-package-decrypt/blob/master/test/basic.js).

```javascript
const fs = require('fs');
const UnityDecryptClient = require('unity-package-decrypt').UnityDecryptClient;
const client = new UnityDecryptClient();

const src = fs.readFileSync('<PATH_TO_DOWNLOADED_FILE>', {encoding:'binary'});
const keySrc = 'e81fcf96aff...';
client.decrypt(src, keySrc).then((data) => {
    fs.writeFileSync('./output.unitypackage', data);
});
```

## How I import the output file into Unity?

![screenshot 2017-11-24 05 51 02](https://user-images.githubusercontent.com/165961/33189260-03722844-d0dc-11e7-86f5-0498efc6db9a.jpg)

## What's the expected result?

Should be able to import decrypted package file into Unity successfully.

**Comment by bengreenier** [comment]
Hey @moscartong - looks like something changed in the `crypto` module - i see a similar failure with the test suite when running with modern node (`8.2.1`) but it works if i revert to old node (`6.7.0`) - i'll isolate the change and work on a fix!

Huge thank you for finding this issue, and communicating it so clearly with the above description! 🚀 💯

**Comment by bengreenier** [comment]
still investigating - but it looks like the behavior of `Decipher.final` is differing by node version.

<details>
<summary>
test run diff
</summary>

with

```
decrypt(packageData, packageKey) {
        return new Promise((resolve, reject) => {
            const decipher = this.createDecryptStream(packageKey)

            decipher.on('error', (err) => reject(err))
            
            console.log(typeof(packageData))            
            console.log(packageData.length)            

            let decrypted = decipher.update(packageData, 'binary')

            console.log(decrypted.length)            
            
            decrypted += decipher.final()
            
            console.log(decrypted.length)            
            
            resolve(decrypted)
        })
    }
```


C:\Users\ben\git\unity-package-decrypt (master) (unity-package-decrypt@0.1.0)
λ npm test

> unity-package-decrypt@0.1.0 test C:\Users\ben\git\unity-package-decrypt
> mocha



  UnityDecryptClient
    √ should construct
    √ should createDecryptStream
3291616
3291600
**3103469**
    1) should decrypt


  2 passing (64ms)
  1 failing

  1) UnityDecryptClient should decrypt:

      AssertionError [ERR_ASSERTION]: 3103469 == 3171523
      + expected - actual

      -3103469
      +3171523

      at client.decrypt.then (e:\vs_workspace\unity-package-decrypt\test\basic.js:34:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.

C:\Users\ben\git\unity-package-decrypt (master) (unity-package-decrypt@0.1.0)
λ nvm use 6.7.0
Now using node v6.7.0 (64-bit)

C:\Users\ben\git\unity-package-decrypt (master) (unity-package-decrypt@0.1.0)
λ npm test

> unity-package-decrypt@0.1.0 test C:\Users\ben\git\unity-package-decrypt
> mocha



  UnityDecryptClient
    √ should construct
    √ should createDecryptStream
3291616
3291600
**3171523**
    √ should decrypt (62ms)

</details>

**Comment by bengreenier** [comment]
v0.2.0 should fix this on modern node. verified by changing the final test to 

```
it('should decrypt', (done) => {
        const client = new UnityDecryptClient()

        const src = fs.readFileSync(`${__dirname}/19248.pkg`, {
            encoding: 'binary'
        })

        const keySrc = fs.readFileSync(`${__dirname}/19248.pkg.key`).toString()
        
        client.decrypt(src, keySrc)
            .then((data) => {
                fs.writeFileSync('out.unitypackage', data, {encoding: 'binary'})
                assert.ok(typeof data != 'undefined')
                assert.equal(data.length, 3291606)
                done()
            })
            .catch(done)
    })
``` 

running it, then opening `out.unitypackage` with unity. Unity package importer enumerates files and begins import, as expected.

@moscartong let me know if you're still seeing this issue - I believe `0.2.0` should fix it.

**Comment by oscarqht** [comment]
Thanks for the quick fix :) However in my case, the same problem still occur. The size of the output file is different though.

I also try to use your unity-package-extract project to extract the output file and got this error:
`Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?`

**Comment by bengreenier** [comment]
darn! is the package you're trying this with actually `vrtk` ? if so i'll try to repro locally and take a closer look

**Comment by oscarqht** [comment]
Yes, it is VRTK😂

**Comment by oscarqht** [comment]
Any update on this issue?

**Comment by bengreenier** [comment]
sorry @moscartong i haven't had a chance to try to repro the failure locally - i did confirm that the test package works as above.

Can you try `npm test` locally within a cloned copy of this repo? If that fails as well that is useful information to have. I would also like to know what version of `node` you are using.

I'll try to make time to repro this locally with the vrtk package in a few hours.

**Comment by bengreenier** [comment]
using the package info defined above and the following versions of node things work for me locally, so I can't repro this one 😕 

Is it possible your original (encrypted content) downloaded incorrectly?

```
Unity: 2017.3.0b5 (x64)

λ node --version
v8.2.1

λ npm --version
5.3.0
```

**Comment by oscarqht** [comment]
Hi bengreenier. I double check this issue again today and found that indeed my encrypted package is corrupted. After downloading it correctly and try again. I could ~~not~~ now decrypt the package and import the result into Unity :)

---

_Sorry for the typo above. I mean I could **now** decrypt the package, not "I could not" :P 
Man I really need to improve my English :(_

**Comment by bengreenier** [comment]
Hey @moscartong just to clarify - you're saying you re-downloaded but you still see the failure occurring?

**Comment by bengreenier** [comment]
@moscartong I just had a chance to repro on another machine and did notice that the package is invalid if you incorrectly write the resulting data to disk.

Please make sure that you do the following (note: the added `{encoding:'binary'}` to the `writeFileSync`):
```
const fs = require('fs');
const UnityDecryptClient = require('unity-package-decrypt').UnityDecryptClient;
const client = new UnityDecryptClient();

const src = fs.readFileSync('<PATH_TO_DOWNLOADED_FILE>', {encoding:'binary'});
const keySrc = 'e81fcf96aff...';
client.decrypt(src, keySrc).then((data) => {
    fs.writeFileSync('./output.unitypackage', data, {encoding: 'binary'});
});
```

See [the docs](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) for more info!

**Comment by oscarqht** [comment]
@bengreenier I mean re-download the package and the decryption is succeeded :) And yes I didn't use `{encoding:'binary'}` to write the file, that's why I fail at the first place. After adding `{encoding:'binary'}` when writing the downloaded package to disk, I have no problem decrypting it :) Thanks for helping me to solve this problem 👍 👍

**Comment by bengreenier** [comment]
Gotcha! Awesome, glad it's fixed! :Tada: I'm going to close this out!
