### ISSUE TITLE
Hey there. I am really sorry

### ISSUE THREAD

**Issue by SHSStudio** [bengreenier/unity-package-decrypt#3]
Hello there.
i am really sorry, i do not company big with "JS" and "NPM" and things.

but i really do not understand

HOW TO USE this ?
can you please explain, how i can decrypt a downloadet File ?

Problem is: 
i use a downloader for download, because Package Manager always quit at 80% this is boring.
the Key i have
the file i can get.

i did install npm .... your things.
but i do not know, what i have to do, to decrypt the File i get ?

Console - help says nothing
npm seems to be something, but not your decrypter.

help :( how to use this ?
Tests i dont know how to use.
how works this ? 

best Greetings.

**Comment by bengreenier** [comment]
I don't think this works anymore, sorry.
